### ISSUE TITLE
Risk boxes mislabeled

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#1]
This used to be configured for eRegistries
Feedback box should be labeled Risks related to obstetric history 
risksANCMED box should be labeled Risks related to medical condition
This stage with UID iXDSolqmauJ which shows up as a risk box should be labelled Risks related to clinical examination

**Comment by AkubaD** [comment]
Also, the boxes should not show if there are no risks. Currently Feedback and risksANCMED  show with the text 'no feedback exist'

**Comment by AkubaD** [comment]
Actually, this may have been in Tracker and not eRegistry, I cannot verify with eRegistry right now cos the MCH program is not working in eRegistry app

**Comment by zepto5** [comment]
Please try this now. I have updated the eRegistry app
