### ISSUE TITLE
Save failed - cannot save stages related to #99 _getHighRiskPregnancy

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#100]
Getting a Save failed error for Yes/No data elements (only). 
The entire event is not saved. And for non-repeatable program stages, you cannot create another event because one has already been created, even though it was never saved. 
Error is
angular.js:11655 TypeError: Cannot read property 'concat' of undefined
    at _getHighRiskPregnancy 
AND
DHIS2EventFactory.updateForSingleValue.then.$scope.currentElement.saved 

Replicate sequence: 
Login: mCHCP_int1 pwd: eReg!234
Create new user (just fill in name, age, village). Create TT History Event in Client register

![image](https://user-images.githubusercontent.com/36447512/40832522-cc2ea61a-658b-11e8-970e-030a11680947.png)

**Comment by AkubaD** [comment]
@zepto5 
@Bekkalizer asked for you to look at this

**Comment by zepto5** [comment]
The error message is fixed, and caused the rules to not run. The events seems to be saved, but for some reason, I can only get them with the admin user. This is most likely a dhis2-core issue. I will do some more investigation and pass it on to the core developers.
