### ISSUE TITLE
 404 error on creation and enrollment of TEI

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#102]
I get this error when I first create a TEI in the Client register.
Appears again when enrolling in another program and everytime I switch between programs.

GET https://bd-eregistry.dhis2.org/dhis/api/29/userSettings/keyTrackerDashboardLayout 404 (Not Found)

![image](https://user-images.githubusercontent.com/36447512/40907110-10fde068-67e3-11e8-8f76-7ab1d44d68ee.png)

**Comment by Bekkalizer** [comment]
This is "just" log noise. We can remove it, but it should not have any functional impact. All the operations in the UI works normally, right?

**Comment by AkubaD** [comment]
Yes it seems to be. I will reopen if any seemingly related issues come up
