### ISSUE TITLE
No actions running on attributes in MCH program, but run in Client register program

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#107]
We have validation rules for several of our attributes such as phone number, completed years of education, ID numbers, etc.
The same attributes are in the 2 programs, and the rules are clones of each other (of course with different program rule variables).
Putting invalid values in the Client register generates the Show warnings we have put in as actions. But do not for the MCH program.
When I look up the rule evaluation in the browser console, they correctly evaluate to true or false based on the values entered. But when the rules have been evaluated to true, the Show warnings do not show in the MCH program, meaning the action has not ran.

Eg phone number validation:
MCH program rule: ruleAtr1016
Client register rule: ruleCRg1015

**Comment by AkubaD** [comment]
Hi @Bekkalizer 
It looks like you fixed this same error 2 years ago:
https://lists.launchpad.net/dhis2-devs/msg44463.html

**Comment by Bekkalizer** [comment]
The source of the cloned program rule used to have a problem with its actions. Can you open, and try to recreate, the program rule actions for the non-working rule?

**Comment by AkubaD** [comment]
Hi @Bekkalizer 
It was not only that rule. I gave that rule just as an example. ALL the validation actions for attributes in the MCH program dont run even though they run in the Client register program.

I deleted and recreated the action in the original rule - no change
I created a new rule with the same  rules and actions (UID x5phI0f3gMm), still not working. Note:This was not a clone of the original rule. 

 I created the rule in another program - MCH Duplicate (UID ACMUH0rDgyd) and it doesn't work there either. Rule UID dFnpcMo05yz

So it looks like the issue is running the rule in the second program enrolled in

**Comment by AkubaD** [comment]
Hi @lukasewvd 
Could you take a look at this? I had discussed with Markus, but it looks like it slipped off our list as we got into other things.
It looks like he had fixed this same error 2 years ago:
https://lists.launchpad.net/dhis2-devs/msg44463.html

**Comment by AkubaD** [comment]
Working now...
