### ISSUE TITLE
Change pop-up asking why you are accesing a woman's record to only pop-up outside the Union of the enrollment org unit

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#109]
The system is currently designed such that if a woman is created in an org unit different from that of the current user, then you get this pop-up message saying that the patient has been found in a different clinic and asking why the user is accessing that record.
In Bangladesh, 3 out of our 4 cadres of healthworkers each act as their own org unit. And a woman will regularly be seen by at least 3 of the 4 cadres. So this message comes up too often.
Could the message be restricted to show only when the woman was enrolled in a UNION different from the current user's? Union is level 5 in the org unit hierarchy,
The message should also say: 'Patient found at another union'
Instead of  'Patient found at another clinic'.

![image](https://user-images.githubusercontent.com/36447512/42823725-8d47b640-89de-11e8-8b50-eb3f4dbc24f1.png)

**Comment by Bekkalizer** [comment]
Lukas - can you have a look at how much work this will be - pointing out that it should not affect the Palestine version

**Comment by lukasewvd** [comment]
This has now been implemented. Regarding the header text I would suggest to use translation to set the desired text.

Link to commit: https://github.com/HRHR-project/e-registry-app/commit/910a38f02f367b6accd2fb9720f7c0fb9a8a0c74

**Comment by AkubaD** [comment]
Hi @RahmanMonjur 
Could you please use translation as Lukas suggested to change the Heading text of the pop up to say 'Patient found at another union' instead of 'Patient found at another clinic'.

**Comment by RahmanMonjur** [comment]
@AkubaD where to translate this text? in translation server, or in DB?

**Comment by AkubaD** [comment]
Hi @lukasewvd 
Could you give @RahmanMonjur direction on where to use translation to change the Heading text of the pop up

**Comment by RahmanMonjur** [comment]
@lukasewvd Did I supplied you those translation? Sorry, I can't remember. If you did it via Google translator, it would be terrible translation.

**Comment by lukasewvd** [comment]
@RahmanMonjur Sorry I was in my own thought. I added it in English. If you want it in Bengali, you can send it to me and I can change it.

**Comment by AkubaD** [comment]
@RahmanMonjur Please remember that the English text is currently wrong. It should say Union instead of Clinic in 2 places: In the heading and in the first sentence of the explanatory paragraph

**Comment by AkubaD** [comment]
@lukasewvd Can you change the English text to say Union then?

**Comment by lukasewvd** [comment]
@AkubaD Not without affecting the Palestine instance.

**Comment by RahmanMonjur** [comment]
@AkubaD @lukasewvd  Translations are:
মা তার বসবাসের স্থান পরিবর্তন করেছে | change her place of residence
মা তার পরিবার পরিদর্শন করতে গিয়েছে | visiting her family
জরুরী অবস্থা | urgent case
মা তার সেবা নেওয়ার স্থান পরিবর্তন করতে চান | desire to chage the place of receiving care
অন্যান্য – উল্লেখ করুন | specify others
স্বাস্থ্য সেবাদানকারী অনুপস্থিত | provider absent

**Comment by AkubaD** [comment]
@RahmanMonjur 
You gave 6 options for the drop down, The current list has only 5. As @lukasewvd  was saying, the list cannot be changed without affecting Palestine.
So what I was suggesting was that you pick one of the EXISTING 5 items on the list and translate it as Provider absent. From what Lukas was saying, I dont think you can add another item to the existing list.
You could add to one of the existing ones eg desire to change place of receiving care/provider absent.

**Comment by AkubaD** [comment]
Yes @lukasewvd  we wanted the options translated as well.
But you cant ADD to the list without affecting Palestine, right? Monjur had added one more item to the dropdown in the translations he sent

**Comment by lukasewvd** [comment]
I have now added the translation for options. As of now, it is not possible to add options. I this is something that is really needed we would have to make a separate implementation. In that case, I would suggest creating a new issue here (GitHub). I will also say, the less we split functionality between the Bangladesh and Palestine the better. The more we split it the more issue prone the system will be.

**Comment by AkubaD** [comment]
Hi @lukasewvd 
@RahmanMonjur will have to resend the translations because they want the 6th option in it somehow. So as I suggested, he will have to translate one of the existing 5 to include the 6th option that they want.

**Comment by RahmanMonjur** [comment]
@AkubaD In that case, we can treat "others" option as provider absent.

**Comment by AkubaD** [comment]
@RahmanMonjur  But the Others option generates a text box for you to fill in what the issue is.  See the screenshot below. Does that work or would it be confusing if you only translate it as Provider Absent? 

![image](https://user-images.githubusercontent.com/36447512/43573587-5dc94b20-9642-11e8-8a05-a03715f0ed35.png)
