### ISSUE TITLE
Union name attribute in search results sometimes shows as UID

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#11]
In the search results list, one of the attributes displayed is Union name. The list is custom drop-down which pulls from the org unit hierarchy for our system.
In the results list, currently a few of the clients returned in the list have UIDs instead of names for Union name. In results list for Village=Bakra, about 25% have UIDs instead of names.
There does not seem to be a pattern that I can see for which are UIDs and which are names

**Comment by zepto5** [comment]
Fixed in commit 87aab06.
