### ISSUE TITLE
Translations of program names, data elements and attributes not showing after Palestine code base deploy

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#112]
Org units, and drop downs are translated when logged in as a Bengali user (intfac or intfwa. password eReg!234)
But program names, data elements and attributes are not. I checked on our training instance (which has not yet been updated), and they are translated. So it looks like this is due to the Palestine update.

1) Attributes and program names in search page not translated. But Union name list is:
![image](https://user-images.githubusercontent.com/36447512/44664265-07fe3180-aa13-11e8-87ff-952d18c51f96.png)

2) Data element names and I-buttons not translated, but option set values are.
![image](https://user-images.githubusercontent.com/36447512/44664190-cd949480-aa12-11e8-927e-1310bec72ed1.png)

**Comment by AkubaD** [comment]
@lukasewvd could you take a look at this?

**Comment by lukasewvd** [comment]
It is working for me, ensure that both interface and database language is set to Bengali. Also try to do a browser cache clean: https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

<img width="708" alt="skjermbilde 2018-08-29 kl 10 26 53" src="https://user-images.githubusercontent.com/6719078/44775601-4bbd7c00-ab76-11e8-9821-22dc87e29df0.png">
