### ISSUE TITLE
Managements show wrong date format

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#113]
Managements should be entered into DD-MM-YYYY format. In the same ANC stage, the gestational hypertension management was created as YYYY-MM-DD, while anemia management was created DD-MM-YYYY. Only the anemia management shows in analytics.

Note that the hypertension risk is created through the same rule as hypertensionr isk, and with the correct date format.
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance/#/edit/programSection/programRule/rulePEx1117

**Also note: the anemia management, the date was selected manually through "management date" calendar selector. This chose date in proper format. But before the date is selected, it pre-selects with incorrect format.**

https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html#/dashboard?tei=dMJd1oenHTk&program=WSGAb5XwJ3Y&ou=Law6euHPccf

![image](https://user-images.githubusercontent.com/36451485/44903947-2d8a8400-ad0e-11e8-8e6b-bfcf0c639cda.png)

**Comment by lukasewvd** [comment]
This should now be fixed with this commit: 4f86008.
