### ISSUE TITLE
Metadata dependency import stuck on importing program stages

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#120]
In doing an update of changes to program rules, program stages, etc, we have been trying to do an import of a metadata dependency export of both our Client register and MCH programs on a staging instance before moving to production. The Client register import worked ok. But the MCH program import gets stuck when it gets to importing program stages for at least 12 hours. Trial run did not reveal any major 
 We tried doing an import of the client register to interrupt the process and then redo the MCH program import. Got stuck again. 
This has happened on 2 different instances at 2 different times. Here is the metadata we are trying to import. 
[MCH_11Apr_metadata.json.zip](https://github.com/HRHR-project/e-registry-app/files/3068608/MCH_11Apr_metadata.json.zip)

@lukasewvd @Bekkalizer What more information do you need to investigate this?
@RahmanMonjur

**Comment by RahmanMonjur** [comment]
It may help you
<img width="567" alt="Screenshot 2019-04-12 at 15 03 35" src="https://user-images.githubusercontent.com/6468891/56025669-64108e80-5d34-11e9-8965-536377aa489d.png">
<img width="1141" alt="Screenshot 2019-04-12 at 15 03 27" src="https://user-images.githubusercontent.com/6468891/56025672-6672e880-5d34-11e9-91dc-e37470c82389.png">

**Comment by AkubaD** [comment]
@Bekkalizer @lukasewvd  could you please look into this? We haven't been able to update trial-related changes to our programs because of this

**Comment by AkubaD** [comment]
Was a user sharing issue - individual users assigned sharing properties but were not in the instance where metadata was being imported. Removed all individual user sharing. Solved the issue
