### ISSUE TITLE
Option sets and Yes/no data elements not displaying 

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#13]
Option sets are positioned strangely, and do not show the options
Yes/No data elements don't show any buttons to check off
Yes only data elements work OK.
See attached file
[option sets and YesNo data elements.docx](https://github.com/HRHR-project/e-registry-app/files/1727146/option.sets.and.YesNo.data.elements.docx)

**Comment by lukasewvd** [comment]
Fixed with this commit: https://github.com/HRHR-project/e-registry-app/commit/2068304d9614da824c750f4692c4733752a534ff
