### ISSUE TITLE
Description/i-buttons needed for data element groups

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#14]
We need i-buttons for 2 data element groups recreated since the v29 upgrade. In regular data elements, the text goes in the ‘Description’ field, which data element groups don’t have. So I think previously Markus hard coded this in.

Data element group name | UID | i-button text
-- | -- | --
Pregnancy and delivery complications | z2OCjflFLxa | Complications that occured during this particular   pregnancy or delivery
Postpartum complications | XKV79R3LG5J | Complications that occurred   during this particular postpartum period

**Comment by lukasewvd** [comment]
Fixed with this commit: https://github.com/HRHR-project/e-registry-app/commit/e40277b19c3d4e59e7e52ad703751e91892dce3d
