### ISSUE TITLE
Designations sectionnow showing for data entry

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#18]
This is probably a Markus issue:
The Designations section within the ANC booking visit program stage did not use to show in events for data entry. I think it is used like the ANCrisks stage for some of the ANC booking visit functionality, and so it is not supposed to show within an event for data entry

**Comment by Bekkalizer** [comment]
It is always hidden by a rule - if you want to see it you must disable or remove the rule hiding it.

**Comment by AkubaD** [comment]
@Bekkalizer It is currently showing and we DON'T want it to show. 
I don't know what rule used to hide it. Could you provide it?

**Comment by Bekkalizer** [comment]
In that case the rule that was supposed to hide it does not seem to be triggered!
Do you see the rule for hiding the program stage in the excel file and maintenance app?

**Comment by AkubaD** [comment]
@Bekkalizer There doesn't seem to be a rule for hiding that section in the Excel file that you provided. I could write a hide section rule, but what is the condition? Is it supposed to always be hidden? This is what is looks like

![image](https://user-images.githubusercontent.com/36447512/37514345-f0eec734-2907-11e8-9af4-018ee9a3274d.png)

**Comment by Bekkalizer** [comment]
Yes, there was s HIDESECTION rules in the original ruleset that had the condtion set to the word true.
