### ISSUE TITLE
Hidden stages for risks and managements now showing

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#2]
This used to be configured for eRegistries
The risks and managements stages which used to be hidden are now available in the options for adding a stage. They should not be available for a user to add an instance of those stages.
They are:
PPCRisks
NNC Risk
ANCRisks
ANCManagements
PPCManagements
NBCManagements

**Comment by zepto5** [comment]
I guess this also was in the tracker-capture app and not the e-registry?
If not, could you please provide a link and a screenshot?

**Comment by AkubaD** [comment]
This was tracker-capture not eRegistry. Closing the issue
