### ISSUE TITLE
Description of report date of Program stage not reflecting in data entry

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#20]
This is an issue we have had before v29.
In the settings for Program stage, there is an option to specify the name of the Report date. What we have put in is not reflected in the data entry screen. It still says Report date.
Eg attached is Previous Pregnancy Stage
[Report date description not reflecting in data entry.docx](https://github.com/HRHR-project/e-registry-app/files/1736192/Report.date.description.not.reflecting.in.data.entry.docx)

**Comment by zepto5** [comment]
Fixed in commit 8e8bb79

**Comment by zepto5** [comment]
Fixed in commit 8e8bb79
