### ISSUE TITLE
Unable to see or edit existing sections

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#21]
We previously had the Programs app separate from maintenance where you could create Sections and edit the sequence of data elements in a section.
With the new functionality put in the Maintenance app, there is a place for creating sections, but it looks like the existing sections were not ported over, and so I cannot make any edits to my existing sections. See the blank section creation window below, which is the ANC Booking visit intervention stage.
Could the old Programs app be brought back temporaritly if it will a while to get the existing sections showing?

![image](https://user-images.githubusercontent.com/36447512/36379886-8f0096fa-1580-11e8-95de-47315355309e.png)

**Comment by Bekkalizer** [comment]
This should work in the updated programs app. Please update the war file with the newest one.
