### ISSUE TITLE
Question: how to get age in years from Age value type attribute

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#22]
Thanks for implementing the Age value type for the eRegistry app.
How do I get the age in years from this new value type? What rule, what variables, what syntax do I use?

**Comment by lukasewvd** [comment]
Hi, AGE is stored as a date. You would need to make an indicator that uses d2:yearsBetween(currentDate, birthDate).

**Comment by AkubaD** [comment]
Thanks!
