### ISSUE TITLE
No longer have ability to order tracked entity attributes

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#23]
With the move of all functionality that used to be in the Programs app into Maintenance, the new interface does not provide ability to arrange attributes in the order you want them to be displayed in data entry view. Similar issue with data elements in program stages.

![image](https://user-images.githubusercontent.com/36447512/36424396-6f3dcba8-1643-11e8-928c-508fefab2b1e.png)

**Comment by Bekkalizer** [comment]
This is registered as a bug on the 2.29 release project: https://jira.dhis2.org/browse/RP229-24
Watch this one - and when it is fixed, update to the latest WAR build on the bangladesh server. Int he meantime it would have to be updated directly in the db.

**Comment by lukasewvd** [comment]
This has been fixed, update WAR-file if you still have this issue.
