### ISSUE TITLE
Search results box distorted

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#25]
The search results box is stretched beyond the background box. Can it be made to stretch together with the search results table?

![image](https://user-images.githubusercontent.com/36447512/36427259-f6f5fcba-164c-11e8-842d-f49e1e112429.png)

**Comment by lukasewvd** [comment]
This has already been fixed, with this commit: https://github.com/HRHR-project/e-registry-app/commit/78890f33b4fc5cf49a188c099d18765c93a02daf. The newest version was probably not deployed when you tested.
