### ISSUE TITLE
Does not clear data for phone number attribute after Show error

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#26]
We have Show error rules running to validate numerical attributes such as ID numbers, years of education, age at marriage.
For all these attributes, apart from Phone numbers, if there is an error, the system clears the data entry field after the show error window pops up. The only ones where this does not happen are those with Phone number value type.
The rule also doesn't always trigger as you change the number entered

![image](https://user-images.githubusercontent.com/36447512/36428229-aa3d4146-164f-11e8-93fd-fd4509ccf150.png)

**Comment by lukasewvd** [comment]
This is not specific for PHONE number it happens to the other tracked-entity-attributes. It happens when you type in the same field after you got the warning message.

**Comment by lukasewvd** [comment]
Fixed with this commit: 19580cf.
