### ISSUE TITLE
Complete event generates 'Server error'

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#27]
I have observed this only in the previous pregnancy stage (uid ) which is one of the specially configured stages for eRegistry. It shows up as a pop-up window for data entry.
When I click complete, I get 'Server error, Please try again later'

![image](https://user-images.githubusercontent.com/36447512/36441200-30d1ddc6-1672-11e8-8405-3e994e2716a7.png)

**Comment by zepto5** [comment]
Cause by same error as: https://github.com/HRHR-project/e-registry-app/issues/30
