### ISSUE TITLE
Complete and exit does nothing

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#28]
When I click on Complete and Exit, it stays in the data entry page and nothing happens. I tried for at least 2 program stages, same result.

![image](https://user-images.githubusercontent.com/36447512/36441290-74052d8c-1672-11e8-93b8-1e031b07bf79.png)

**Comment by zepto5** [comment]
Caused by same error as: https://github.com/HRHR-project/e-registry-app/issues/30
