### ISSUE TITLE
MCH program referrals not showing

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#29]
No referrals are showing. Other rules such as risk box displays are running ok

**Comment by Bekkalizer** [comment]
Hey, can you add some more details here on what is not showing where. And reproduction steps?

**Comment by AkubaD** [comment]
I have a series of rules related to selecting a data element from a data element group in the Previous pregnancy stage (uid PUZaKR0Jh2k) which then displays text in the feedback widget (Obstetric Risks box) and creating a referral event.
Here is the rule. The Display text action of the rule works, but the Create event does not. No Create event rules I have created work - no referrals are being generated.  
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance/#/edit/programSection/programRule/ruleprv1113
