### ISSUE TITLE
Landing page shows list of all clients without search

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#3]
This used to be configured for eRegistries
Landing page should not show all clients in the selected org unit. 
Should force search.
Search should be limited to 5 results. If more than 5 results, should ask for more search parameters
Should not be able to register without searching

**Comment by zepto5** [comment]
Are you sure this is in the e-registry app?
This sounds like the tracker-capture app. 
If not, could you provide a screenshot?
