### ISSUE TITLE
Cannot enroll tracked entities in MCH program only - even as super user

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#30]
This seems to have appeared today, but may have been from yesterday or day before - I've been testing with existing tracked entities, so I did not notice until today.
Whether you try to enroll a new tracked entity, or enroll an exisiting tracked entity into the MCH program, when you click Save, nothing happens. No errors, nothing. 
I have tried making most of the attributes not mandatory, and only enter in minimum information - Name and Village name, which are both just text fields. Still nothing

**Comment by iambodo** [comment]
I can verify this. I'm a superuser and assigned to the correct user group for MCH program access (view and write).  The button for "Save" on the register new TEI page for MCH program does not work. It should take you to the program splash page to enter new stages, but does **nothing**.

![image](https://user-images.githubusercontent.com/36451485/36539351-d3286bca-17d6-11e8-9155-ef7e7e9b6016.png)

![image](https://user-images.githubusercontent.com/36451485/36539329-bf9112e2-17d6-11e8-8634-8ffc81ee3826.png)


This may be related to a separate issue: there is no button to enroll in a new program when navigating through the TEI enrollment main page (list of available stages). Making a separate bug report for that.

**Comment by lukasewvd** [comment]
Can you do the same steps again and send us the server log from after you have pressed the "Save and continue" button?

**Comment by iambodo** [comment]
Sure
angular.js:11655 unknown datatype:AGE
angular.js:11655 could not find variable to count: MCH_LowBirth
angular.js:11655 Variable SMS - Initial Gestaional Age was not defined.
angular.js:11655 Expression with id rule:ruleprv1120 could not be run. Original condition was: d2:count(MCH_Comp_Post_Eclampsia') >0 - Evaluation ended up as:d2:count(MCH_Comp_Post_Eclampsia') >0 - error message:SyntaxError: Invalid or unexpected token
angular.js:11655 Expression with id rule:ruleprv1126 could not be run. Original condition was: d2:count(MCH_Comp_Post_PPH') >0 - Evaluation ended up as:d2:count(MCH_Comp_Post_PPH') >0 - error message:SyntaxError: Invalid or unexpected token
angular.js:9866 POST https://bd-eregistry.dhis2.org/dhis/api/29/enrollments 500 (Internal Server Error)

![image](https://user-images.githubusercontent.com/36451485/36545606-91dd1432-17e9-11e8-8a05-8f4f4c9b4772.png)

**Comment by lukasewvd** [comment]
Thanks, but that is **client-side** error log. **Server log** is produced by the server. @Bekkalizer can probably help you with how to obtain the log.

**Comment by iambodo** [comment]
I dont have access to those unfortunately. I will check with system admin in bangladesh.

**Comment by zepto5** [comment]
Issue is caused because of program notifications. Server rule engine is called because of existing program notifications. The rule engine needs to be updated before program notifications can be used. A temporary work around is to delete the program notifications untill this is fixed.

**Comment by zepto5** [comment]
Should be fixed in the newest build. Please install the latest war and test this again.

**Comment by lukasewvd** [comment]
Closing issue, tell us if you still are having this issue and we will re-open it.
