### ISSUE TITLE
cannot enrolling in a new program from TEI enrollment page

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#31]
There is no way to enroll in a new program from the TEI enrollment splash page (the list of available stages in a program).

Im a superuser assigned to the user groups for accessing the client register and MCH program,

I can create a tracked entity through Client Register.
![image](https://user-images.githubusercontent.com/36451485/36538961-7c7e830a-17d5-11e8-9d02-d448d87a214b.png)

But when I switch to MCH program from the dropdown, there is no way to enroll in the program, no plus button to "please enroll at right".
![image](https://user-images.githubusercontent.com/36451485/36538912-5f9204b0-17d5-11e8-822b-62348b54a4fb.png)

EDIT: to clarify, one can click "Add New" (enrollment)... but the button at the bottom of the attributes page does not create a new enrollment.
![image](https://user-images.githubusercontent.com/36451485/36546821-a8fbac8e-17ec-11e8-8a82-afbf00667e9c.png)

BUT if I have a TEI already enrolled in the MCH program, the same error occurs when trying to enroll in the Client Register.

Here is an entity enrolled in MCH
![image](https://user-images.githubusercontent.com/36451485/36539192-3c8bacd6-17d6-11e8-860c-81bd9e8335d1.png)

And when opening the entity in the client register... no button to enroll.
![image](https://user-images.githubusercontent.com/36451485/36539156-1e221370-17d6-11e8-859e-86d8fbe14a0e.png)

**Comment by zepto5** [comment]
Closing because of duplicate :https://github.com/HRHR-project/e-registry-app/issues/30
