### ISSUE TITLE
ordering program stages by time of event

### ISSUE THREAD

**Issue by ereg-bd** [HRHR-project/e-registry-app#32]
The ordering of program stages is left to right, oldest to most recent.

See here, position of the event whether it is on 2-25 or 2-26. 
![image](https://user-images.githubusercontent.com/36739826/36683464-eafa986e-1b1d-11e8-8303-82958b12b463.png)

![image](https://user-images.githubusercontent.com/36739826/36683482-fb359f8a-1b1d-11e8-943b-9572a5028fc3.png)

However this only orders by date, not time. 

If I enter one TT vaccine delivery on Day A at Time 12:00, then another on Day A at Time 12:01, the "Most Recent" event is furthest to the left.
![image](https://user-images.githubusercontent.com/36739826/36683681-7b48efec-1b1e-11e8-9c63-7358c3c50ad0.png)

![image](https://user-images.githubusercontent.com/36739826/36683702-8b886eaa-1b1e-11e8-8dc8-895bba1e1e5a.png)

**Comment by zepto5** [comment]
Sort order fixed in this commit: 63c031f
Ordering by sortingDate(eventDate or dueDate) then by created.
Ordering is now:
oldest -----> newest
