### ISSUE TITLE
Disable Search and register for all programs except Client Register program

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#34]
The workflow requested by the Research team is to have users search for and create new tracked entities only in the Client Register program (uid ZBIqxwVixn8). Any data entry for tracked entities in another program will have to be done by switching to that program (via the drop-down of available programs) while you are already in the tracked entity's record.
We would therefore like the UI of the Browser to be like how it is in Palestine, where searching and registration is done within a default program that you do not select -in our case, the Client Register program (uid ZBIqxwVixn8).
The drop-down of available programs should not be made available, and all searches and registration would be done in the Client register program. Enrollment into another program would be done within the tracked entity's record. 

See image below: Program selection should not be available in the search/registration page
![image](https://user-images.githubusercontent.com/36447512/37148784-97902efc-22c3-11e8-91aa-94bb6be8a9ee.png)

**Comment by Bekkalizer** [comment]
Will users have access to more than one program? You might be seeing the dropdown because you are logged in with admin.

**Comment by travellingyak** [comment]
The users will have Access to both programs.   We would like them to only initially enroll in the Client register for privacy reasons.

**Comment by Bekkalizer** [comment]
What we could to is hardcode that the mch program is preselected when you have more than one.

**Comment by travellingyak** [comment]
actually...it would be the other way around...hardcode the Client register for enrollment.  everyone is allowed to register there, then then can add to the MCH program later.

**Comment by travellingyak** [comment]
just to add that we have already made this happen in the android app

**Comment by AkubaD** [comment]
Hi Markus. Is there an update on this
Do you have any other questions to be answered

**Comment by Bekkalizer** [comment]
Lukas is looking at it now - I suggest that we preselect the client register program when that exists, but keep the list visible and changeable at the top of the screen.

**Comment by lukasewvd** [comment]
I have implemented a solution based on @Bekkalizer 's comment: 1f0ee74

**Comment by AkubaD** [comment]
Could you please implement this as requested in the submitted issue? As a super user, your solution has been able to limit my view of programs in the search page to only the Client register and MCH program, when there are several other programs available. So it should be possible to limit to only the Client register program as requested, right?

**Comment by lukasewvd** [comment]
@AkubaD My solution does not limit view of program, after checking https://bd-eregistry.dhis2.org 
multiple of your programs have not been assigned orgUnits.

**Comment by lukasewvd** [comment]
@AkubaD Can this issue be closed?
