### ISSUE TITLE
Make new enrollment link into button

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#35]
The UI for enrolling an existing Tracked entity into a new program is not very intuitive. It is a faint link to the right that almost everyone misses.
Could you please Replace the 'Add new' link with a button called 'Enroll into new program'? 
The text 'Selected Program' also does not seem to serve any use - it's in a box listing the enrolling clinic. Could that text be removed (if it is not too much trouble), to make space for the new Enrollment button?

![image](https://user-images.githubusercontent.com/36447512/37150698-91cc37de-22ca-11e8-9f88-3d77208af0ca.png)

**Comment by AkubaD** [comment]
Hi Markus
I checked in with Mike about this and he is okay with Changing the link into an Enroll button since Palestine only uses one program and would not use this functionality anyway.
Could you let us know when this could be implemented

**Comment by Bekkalizer** [comment]
Ok we can change it as requested. The change will affect the Palestine also, for everyone enrolling into the program for the second pregnancy on.

**Comment by AkubaD** [comment]
Oh yes, that's true. But Mike agreed that the link was obscure and a button would be better.

**Comment by lukasewvd** [comment]
Requested changes have been made: 
<img width="540" alt="enrollmentwidget" src="https://user-images.githubusercontent.com/6719078/37522662-e00f1dac-2924-11e8-84a3-92163d7b31b7.png">
