### ISSUE TITLE
Create data entry form freezes often

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#36]
In Maintenance/Programs/Program stages/Create data entry form, while working in 'Section', the page seemed to freeze: All these actions would do nothing:
clicking 'Save', clicking 'Cancel', clicking on 'X' to remove data elements, editing name of section - when you click on the checkbox to save your change, it reverts to the original text.

One of what caused this was changing the name of a section - it didn't work, and then I couldn't save or do anything
Also potentially going from 'Create data entry' to Assign Data elements, without saving

**Comment by Bekkalizer** [comment]
Please try and get the latest 2.29 DHIS2 WAR file. If the problem still persists, report the problem in jira.dhis2.org

**Comment by lukasewvd** [comment]
@AkubaD I'm closing this issue since it is not related to the e-registry app.
