### ISSUE TITLE
Changing name of Section does not work

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#37]
To change the name of a section, I click on the pencil edit button, make the change, and then click on the check. I was able to do this once today. I have not been able to do it again. After clicking the check, it reverts to the original text.
Once you try to make the change, that page freezes, and you cannot save, cancel or make any changes to the program stage.
See related issue #36

**Comment by Bekkalizer** [comment]
Please try and get the latest 2.29 DHIS2 WAR file. If the problem still persists, report the problem in jira.dhis2.org

**Comment by Bekkalizer** [comment]
All DHIS2 WAR files can be found here:
https://ci.dhis2.org

Here is the direct link to the latest 2.29 file:
https://ci.dhis2.org/job/dhis2-2.29/lastSuccessfulBuild/artifact/dhis-2/dhis-web/dhis-web-portal/target/dhis.war
