### ISSUE TITLE
Follow-up: Function indicating user in Control user group

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#39]
Hi Markus and Lukas
We discussed previously about the need to write program rules with conditions based on if a user is intervention or control.
You had mentioned you could create a function that would return True if a user was control.
With 2.29, we are allocating users to control or intervention using User groups, and not user Roles as we had previously discussed.
Could you create a create a function that would return True (or some specific value) if a user belongs to this User group: https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance-user/editUserGroupForm.action?userGroupId=684787

**Comment by AkubaD** [comment]
Discussed an update to this request with @lukasewvd . Waiting on @Bekkalizer  for ideas on how to implement this request as follows:
The initial requested function to return a Boolean - control or not control
We actually have 4 categories of users - control, intervention, non-randomized, and those outside the research area. It is quite probable that the research needs would require me to not just know who is intervention and control, but which of these 4 user groups they belong to. So could you implement the function to return eg an integer representing one of the 4 user groups?
These 4 groups would be mutually exclusive. But each user would belong to at least one other user group (not one of these 4). They would belong to one related to what type of worker they are - eg facility based or field worker.
The 4 groups with UID are:
Control- tnXCdap5Ucc
Intervention- s2v08tz7BdK
Non-randomized- Q3HJtUe9Qfc
UHC(outside research area)- DbQUVY5GA7y

**Comment by lukasewvd** [comment]
I have added a function to program rules called: d2:hasUserRole. It can be used like this: d2:hasUserRole( 'x123x123' ), where the paramater is the id of a user role. The function will return either true or false depending if the user has the role that is checked.

**Comment by AkubaD** [comment]
Hi @lukasewvd. Thanks for the update.
With the change in how user roles and user groups work in v29, the function needs to be based on User role and not user group. I detailed that in creating the issue, and the IDs I provided were of user groups. 
Im hoping you meant user group and not user role...

**Comment by Bekkalizer** [comment]
Is it just as easy to use the user roles for you Akuba? The users can still have user roles like before, and the user roles is already cached in the app, so we dont have to do a new call to get the user groups.

**Comment by lukasewvd** [comment]
@AkubaD Could you please give an answer so we can proceed?
