### ISSUE TITLE
Coupling of Booking and subsequent visit stages

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#4]
This used to be configured for eRegistries
ANC Booking and ANC subsequent visit used to be coupled so that ANC booking would be the first instance of those 2 stages created, And once a instance of ANC booking exists, then an instance of ANC subsequent visit could be created.
Should couple 
1) ANC Booking intervention with ANC subsequent visit -intervention
2) ANC Booking control with ANC subsequent visit -control
3) PNC Booking visit-mother with PNC subsequent visit-mother
4) Newborn care first visit with Newborn care subsequent visits

**Comment by Bekkalizer** [comment]
Please add UIDs, and we can couple these.

**Comment by AkubaD** [comment]
How do you get uids of stages in this new system in Maintenance?

**Comment by AkubaD** [comment]
Used api for the uids. But that is something to be fixed - I'll put in a new issue.
1) ANC Visit Control: piRv8jtcLQV    IlSUGDq9QDc
2) PNC visit mother: w0pwmNYugKX    dqF3sxJKBls
3) Newborn care: FRSZV43y35y    fSE8JyGdsV6

**Comment by lukasewvd** [comment]
Should be fixed with this commit: https://github.com/HRHR-project/e-registry-app/commit/0921a198add987ea3a539ce16257ef658908cb0f. Please test!
