### ISSUE TITLE
Missing 'Show details' for Program stages in Maintenance

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#41]
With the move of functions that used to be in the Programs app to Maintenance, we now can't see details of a program stage, including its UID from Maintenance. Could 'Show details' be added to the options (Edit, Sharing, Delete...) when you click on the 3 dots?

![image](https://user-images.githubusercontent.com/36447512/37466409-f10845a6-285d-11e8-9171-7f9d499e68f1.png)

**Comment by Bekkalizer** [comment]
Please report in jira.dhis2.org <http://jira.dhis2.org/> as a improvment issue.

**Comment by lukasewvd** [comment]
Closing issue since it is not related to the e-registry-app.
