### ISSUE TITLE
Report date not autopopulating for a particular stage

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#42]
Affected stage: PUZaKR0Jh2k
Report date (called Pregnancy outcome date in this stage), auto-poulate with the current date when a new instance was created. I believe it used to do this, but no longer does.
Other stages with similar configuration autopopulate, so I don't know what the issue is.
Example, compare to stage uD4lKVSbeyB

![image](https://user-images.githubusercontent.com/36447512/37468463-60382de2-2863-11e8-989d-ebf6f8a29aa5.png)

**Comment by lukasewvd** [comment]
@Bekkalizer Correct me if I am wrong, but I think it was made like this on purpose. I see there is code that checks for the id and cleans the date (new-event-controller.js l:79-83).

**Comment by AkubaD** [comment]
@lukasewvd  you're probably right since this stage is (always) recording a previous event. Thanks!
We would want the same to be done for the Control version of this stage then: uD4lKVSbeyB
Also for that stage to be configured like the intervention version (PUZaKR0Jh2k) in display and summary list

**Comment by lukasewvd** [comment]
The program stage should be changed now. Please test and confirm.
