### ISSUE TITLE
Managements/Create event not showing again

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#43]
This used to work just a week ago or so- managements showing at the bottom of the sheet; 
Also, entries in the Clinical risk box which are created with Create Event, listing date and gestational age. They are not showing as well
Only the risk boxes with Display Text rules are currently working

**Comment by Bekkalizer** [comment]
Are you sure you did not accidentally open the tracker capture app instead of the eregistry app?

**Comment by AkubaD** [comment]
Nope. Its the e-registry app
https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html

**Comment by Bekkalizer** [comment]
The problem turned out to be date format. The date format of the server was changed some days ago, and then the problem started. The issue that causes the behavior we see here is that the event creation for managements fails (webpack:///./scripts/dhis2.angular.services.js:2271).

**Comment by Bekkalizer** [comment]
@lukasewvd, @AkubaD changed the date format back to the working(but wrong) date format tonight. She will change the date format again tomorrow morning to the non-working(but correct) date format. Can you have a look and try to find a fix?

**Comment by AkubaD** [comment]
I have changed to the  non-working(but correct) date format dd-mm-yyyy. BUT, because of this other issue #38, I had deleted all rules to repost. But now, no rules are posting at all from the Excel sheet. So there are currently no rules in the system that use dates that generate managements/referrals.

**Comment by lukasewvd** [comment]
I have pushed a fix for this issue. I would appreciate if you could test the fix.

**Comment by AkubaD** [comment]
@Bekkalizer @lukasewvd Sorry. The notifications go to another email.
Yes! The rules are posting and they are repost ok as well. But the managements are not showing - the date format is in the non-working(but correct) date format dd-mm-yyyy

**Comment by lukasewvd** [comment]
Remember that new deploy of the app has to happen before the changes are reflected in your system. 😀

**Comment by AkubaD** [comment]
Hi Markus
I'm getting this internal conflict error again. I tried a couple of new rules and they created okay and when I reposted them, they posted ok. But, for rules that already existed before today, when I tried posting, I got the internal conflict error again
Debug gives:
{"httpStatus":"Conflict","httpStatusCode":409,"status":"ERROR","message":"One more more errors occurred, please see full details in import report.","response":{"responseType":"ObjectReport","uid":"ruleTop1006","klass":"org.hisp.dhis.programrule.ProgramRule","errorReports":[{"message":"Found matching object for given reference, but import mode is CREATE. Identifier was UID, and object was Top Label: Show name & age [ruleTop1006] (ProgramRule).","mainKlass":"org.hisp.dhis.programrule.ProgramRule","mainId":"ruleTop1006","errorCode":"E5000"}]}}

{"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR","message":"could not execute statement"}
