### ISSUE TITLE
'High risk' flag and 'Unmanaged condition' do not show

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#44]
I used both CreateEvent with stage RefHighRisk, as well as the explicit action of Assign true to #{refertohighriskclinic}
High risk flag never shows
'Unmanaged condition' also does not show

**Comment by Bekkalizer** [comment]
Can you attach a screenshot? Did you open the e-registries app or the standard tracker?

**Comment by AkubaD** [comment]
eRegistries app https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html
See below: risk boxes created with Display Text show, but not those with Create Event
![image](https://user-images.githubusercontent.com/36447512/37474944-d35b4b66-2871-11e8-998d-e88672303f05.png)

**Comment by AkubaD** [comment]
Turns out I hadn't posted the rules for those
