### ISSUE TITLE
Problem with stage coupling - ANC, PNC and Newborn

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#45]
DISREGARD this and read subsequent comment below

Could you please couple the PNC stages for mother and child as has been done for ANC booking and ANC visit?
Mother: 
PNC Booking - w0pwmNYugKX
PNC subsequent visits - dqF3sxJKBls

Newborn
Newborn care Booking visit - FRSZV43y35y
NBC subsequent visits - fSE8JyGdsV6

**Comment by AkubaD** [comment]
There seems to be a problem with all the stage couplings- ANC intervention, ANC control, PNC mother, Newborn care. 
The coupling has been done (PNC subsequent visit shows both Booking and PNC visit when you look at multiple PNC entries),  but the Booking visits are showing up on their own in the menu of available stages, and you cannot create an additional stage instance (since Booking visits are not repeatable)
What it should look like is 
1)No Booking visits should be seen in the menu of stages available, and 
2) the Subsequent stages should behave the way they are behaving now - showing the booking visit when there are multiple visits.
I tried to include screenshots, but I keep getting processing errors - maybe because I'm in Bangladesh.

**Comment by lukasewvd** [comment]
Hi @AkubaD, the booking visits are not showing up for me in the menu. Have you cleaned you cache?
<img width="1674" alt="bookingvisit" src="https://user-images.githubusercontent.com/6719078/37585508-abf19108-2b59-11e8-840f-7419a4c65a6c.png">

**Comment by AkubaD** [comment]
Thanks @lukasewvd Looks like that was the problem. I usually use new incognito windows, so I generally don't often clear cache
