### ISSUE TITLE
Increase width of popup search list 

### ISSUE THREAD

**Issue by RahmanMonjur** [HRHR-project/e-registry-app#46]
Please increase width of the search popup window 1 inch or 2. Now, its too narrow, showed in Chromebook.

**Comment by lukasewvd** [comment]
Fixed with: 2bd166b.

**Comment by RahmanMonjur** [comment]
It seems same width as before. I cleared the cache. By the way, do I need to redeploy the app?

**Comment by lukasewvd** [comment]
@RahmanMonjur The app has not been deployed yet. I usually deploy at the end of the day (17:00/05:00 CET) otherwise you can deploy it, if you want to check the change now.
