### ISSUE TITLE
Bug causing created events to stay even when condition has been reversed

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#48]
Talked to @Bekkalizer about this and he identified a bug that causes it. I'm recording it here to help track it.
The issue: If you trigger a rule (eg Click Yes) that generates a management (Create event), and then you immediately Click No, the management created persists. And you have a mamangement that does not match your data
Examples in ANC visit
-Asthma
-Excessive vomiting (generates both management and clinical risk box entry)

**Comment by lukasewvd** [comment]
This has now been fixed and should be ready for testing/use in the next deploy.
