### ISSUE TITLE
'Status' in Previous pregnancy stage and Clinical risks stage

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#50]
What is the use of the 'Status' in the Previous pregnancy stage summary and the Clinical risks box? In the managements, we see that completing them takes away the 'Unmanaged condition'. But we are not clear on the use of the status in Previous pregnancy summary or the Clinical risks box. If they have no use, could they be taken out? They would be confusing to our health workers and take up unnecessary space in the already-crowded screen.

![image](https://user-images.githubusercontent.com/36447512/37773854-ffa4f1d2-2dde-11e8-851f-7318b9a8f5af.png)

**Comment by lukasewvd** [comment]
@Bekkalizer, could you provide a comment on this?

**Comment by lukasewvd** [comment]
As requested in #54 the "Status" column has been hidden. Keeping the issue open till questions are answered.
