### ISSUE TITLE
Facility birth Flag like High risk flag

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#56]
Some pregnant women (who may or may not be High risk flagged already), are to be flagged for Facility delivery.
Could we have an 'Advise facility birth' flag that acts like the High risk flag?
- Colored red
-In Bold
-Set/displayed by a program rule in the indicators widget, next to, but separate from the High risk flag

The high risk flag is implemented by a function V{highRiskPregnancy} as below. I don't really need the function - I can write a rule to satisfy the conditions for facility birth and Display text as the action. But there is obviously something that makes the high risk flag Display text call special in displaying the High risk flag text in red and bold. I tried doing 'Display text of 'Facility birth' in Indicators, and it just showed up as regular black text.

true |   | actonTp1011 | ruleTop1011 | ASSIGN |   | #{markedAsHighRisk} | V{highRiskPregnancy}
-- | -- | -- | -- | -- | -- | -- | --
V{highRiskPregnancy} |   | actonTp1012 | ruleTop1012 | DISPLAYTEXT | indicators | High risk pregnancy |

**Comment by lukasewvd** [comment]
I have added it now, I have not tested it so would appreciate if you could do it.
