### ISSUE TITLE
can only access eRegistry through superuser role

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#6]
this is an urgent error as it is currently restricting eRegistries access to superusers.
Ive cleared cache and checked that its the same Org unit and user role has access to programs (they had access prior to 2.29 too) so Id expect its a new permission.

I can access the eregistries app through superuser, but not through those with the "Tracker Data Entry" user role.

I have added the See Eregistries permission to the Tracker Data Entry user role
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance-user/showUpdateRoleForm.action?id=645821

I can see it when signed in as a superuser
![image](https://user-images.githubusercontent.com/36451485/36162216-112bff42-10e6-11e8-99d7-e22c86d702cb.png)

But cannot see any programs when signed in as HA1 or as element_test1
![image](https://user-images.githubusercontent.com/36451485/36162022-98230e74-10e5-11e8-8fa4-cbc69f493d42.png)

**Comment by zepto5** [comment]
Can this be closed now?

**Comment by lukasewvd** [comment]
Closing issue, if this is still an issue tell us and we will re-open it.
