### ISSUE TITLE
Can't translate person entity type through context menu in UI

### ISSUE THREAD

**Issue by RahmanMonjur** [HRHR-project/e-registry-app#60]
Translation option for Tracked Entity Type is also not available in translator app.

**Comment by lukasewvd** [comment]
This is a dhis-core issue, could you please report it on the JIRA site (https://jira.dhis2.org)?

**Comment by RahmanMonjur** [comment]
Jason asked to communicate with Markus, Lukas, or other experts.

**Comment by lukasewvd** [comment]
As stated in my previous comment, this is not directly related to the e-registry app, therefore you can create an issue on JIRA(https://jira.dhis2.org) where the relevant devs will be notified of this issue.

**Comment by RahmanMonjur** [comment]
I've communicated with Jason and sent errors (server logs), and he was saying that it would be a database issue.

**Comment by lukasewvd** [comment]
As of now translation of tracked entity type is not supported, it needs to be implemented.

**Comment by RahmanMonjur** [comment]
FYI, It works in live.dhis2.org

**Comment by lukasewvd** [comment]
You are correct, my fault. I see there is a 500 Internal Server Error when I try to save the translation. @Bekkalizer any ideas?
