### ISSUE TITLE
Union Name attribute selector shows other OU types on registration page

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#64]
On the registration page, the "union name" attribute shows the full tree.
![image](https://user-images.githubusercontent.com/36451485/38417777-f39aa078-3999-11e8-8880-9f418d59f81c.png)

When searching for OU in eReg app, it restricts to only the Unions
![image](https://user-images.githubusercontent.com/36451485/38417794-03132f5c-399a-11e8-8fc5-b583cfa1856d.png)

**Comment by lukasewvd** [comment]
This should be fixed with the next deploy.
