### ISSUE TITLE
Registration OrgUnit tree is different than Search OrgUnit tree

### ISSUE THREAD

**Issue by RahmanMonjur** [HRHR-project/e-registry-app#65]
Registration OrgUnit Union tree is containing below level of Unions which is different than search OrgUnit Union tree. Moreover, when you collapse a tree node, then expand/collapse icon disappears. Also, need to delete Matlab UHCs from Union lists as they're health facilities.

**Comment by RahmanMonjur** [comment]
Yes @iambodo, app is deployed and updated. Still the Unions are containing child nodes in Registration page (Search page is OK). However, its not an urgent issue now, but need to be solved at sometime.

**Comment by lukasewvd** [comment]
I have done some improvements to the orgUnit tree. It should function better in the next deploy.

**Comment by RahmanMonjur** [comment]
@lukasewvd Registration orgUnit is containing two nodes ('JoBQEuzxohv','NzTpSVrwBcE') which is not applicable here. There are also note in search orgUnit.

**Comment by lukasewvd** [comment]
Thanks for the heads up, I have fixed it now.
