### ISSUE TITLE
Completing ANC1 intervention prompts creating ANC1 control

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#69]
When you click Complete for the ANC1 stage (WZbXY0S00lP), it prompts to schedule a follow up appointment for ANC1 control (piRv8jtcLQV). 
1) ANC1 intervention should be coupled with ANC subsequent visit intervention (edqlbukwRfQ). 
2) This is for a user that has read access to the ANC1 control, so they should not even be able to create an instance of this stage

![image](https://user-images.githubusercontent.com/36447512/38734100-a7bd61b4-3f24-11e8-892d-5f6d8ed59433.png)

**Comment by lukasewvd** [comment]
Referring to mail from Markus about this being an issue with the settings, not a bug.

**Comment by AkubaD** [comment]
Hi @lukasewvd 
I responded to Markus's email: It is a bug because the stage that should be suggested for addition should be the ANC subsequent visit stage (which is supposed to be coupled to ANC1 intervention), or at worst, the same stage which is ANC1 intervention. It should not be ANC1 control (which should not have any connection to ANC1 intervention).
For users who have access to both the control and intervention stages (admin and intervention users), it suggests the ANC1 control when you complete the event, For Users who have access only to the intervention stages, it suggests ANC subsequent visit intervention (correctly)

**Comment by lukasewvd** [comment]
Okay, could you give me a detailed list of steps on how to reproduce this issue? On you online instance I can not see ANC1 intervention.

**Comment by AkubaD** [comment]
@lukasewvd 
I think your user is an admin user, so you should be able to see this.
Create a new client. Fill in a few data elements (click a couple of Yes' in Medical risks eg Asthma) and Click complete.
You should see the pop up suggesting to create an instance of ANC1 Control. It should be ANC intervention instead

**Comment by lukasewvd** [comment]
With ANC1 I assume you mean ANC 1st visit. This is how the programStages were ordered:
![skjermbilde 2018-04-17 kl 10 00 20](https://user-images.githubusercontent.com/6719078/38856504-f127f206-4226-11e8-8363-03ef0a62e89f.png)

But if you change the order to the one below, the next event prompt works as intended:
![skjermbilde 2018-04-17 kl 10 00 00](https://user-images.githubusercontent.com/6719078/38856564-16fc3280-4227-11e8-977b-9ac3cadc2b38.png)

@Bekkalizer Could you answer if that is intended behaviour or if this is something that normally should be "hard coded"?
