### ISSUE TITLE
New: Implement age value type as in Tracker 

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#7]
Earlier, before my browser switched to eRegistry fork, I was able to use the Age data value type and it was great! You have the option of entering an age in years with months and days (optional) and it generates the birth date. We need this data value type for Bangladesh since they usually don't know the exact birth date.
Could we have this implemented in the eRegistry fork/app?

**Comment by Bekkalizer** [comment]
Adding standard tracker functionality in tracker is manual merge work, including this age data type.

**Comment by lukasewvd** [comment]
Implemented with this commit: https://github.com/HRHR-project/e-registry-app/commit/91be8805416f750e7a9474e2b2f044056aaccc50

**Comment by AkubaD** [comment]
Hi @lukasewvd There is something strange going on with the Age value type. Rules that I have written to calculate age no longer work - I get age=2018 using d2:yearsBetween function. When I did display text of the Age/birthdate itself (not calculated age), it printed 'False'. So I think the solution you came up with has somehow been reversed

**Comment by lukasewvd** [comment]
Hi @AkubaD, could you test if changing the date format to YYYY-MM-DD does anything? I am suspecting that the date format is not converted before calculations.

**Comment by AkubaD** [comment]
Hi @lukasewvd  I changed the date format. No difference

**Comment by lukasewvd** [comment]
@AkubaD Okay, thanks for testing I will look into it.

**Comment by lukasewvd** [comment]
@AkubaD Do you perhaps have the name of a program rule I can check?

**Comment by AkubaD** [comment]
This rule calculates age
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance/#/edit/programSection/programRule/ruleAtr1008
This rules displays it in the Indicator widget - and that's where you see that it is not working - constantly displays age as 2,018
https://bd-eregistry.dhis2.org/dhis/dhis-web-maintenance/#/edit/programSection/programRule/ruleTop1006
This rule

**Comment by lukasewvd** [comment]
I have commited a fix that should handle this issue, please test (when new deploy is done) and give me feedback.
