### ISSUE TITLE
Event Analytics not loading

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#71]
500 Error when loading the EVENT resource in analytics

![image](https://user-images.githubusercontent.com/36451485/38808412-672986ce-4180-11e8-8cfd-f02eb0b5d354.png)

![image](https://user-images.githubusercontent.com/36451485/38808370-33c288bc-4180-11e8-9ad9-9def9bff103e.png)

I am able to load enrolment count for client register but *no other program indicators.*

**Comment by iambodo** [comment]
and FYI, using admin level user, cleared cache, run resource tables repeatedly.

**Comment by lukasewvd** [comment]
This is not a code bug, but a server configuration issue. The error that is printed is: **"Out of shared memory Hint: You might need to increase max_locks_per_transaction"**.

**Comment by iambodo** [comment]
FYI, Monjur fixed this. New Limit set to 1000. Previously max locks setting was disabled, and default set to 64.
https://www.postgresql.org/message-id/a7c00d4b0911191722l4354168ajfd06f6cc7cc1ed82%40mail.gmail.com

Event reports now works!
![image](https://user-images.githubusercontent.com/36451485/38920185-f358de06-42f2-11e8-86af-0df5213d1614.png)
