### ISSUE TITLE
v2.29 dashboard not displaying event reports (Palestine dev)

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#73]
freezing with 500 internal server error for event reports
![image](https://user-images.githubusercontent.com/36451485/38865599-83f325e4-423e-11e8-9e60-1373704d79af.png)

receiving the max locks error: {"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR","message":"ERROR: out of shared memory\n  Hint: You might need to increase max_locks_per_transaction."}

example error: https://hrhr.dhis2.org/dhis/api/29/analytics.json?dimension=dx:XOqKUoalBfx;Yxql8OHwGUs;bH09RGQsjeq;sUJqoqIu9OZ&dimension=pe:LAST_MONTH;THIS_MONTH&filter=ou:GD7TowwI46c&displayProperty=NAME&skipMeta=true&includeNumDen=true

pivot tables for aggregate data appear to be loading (see "data monitoring" dashboard)

**Comment by lukasewvd** [comment]
Most likely same issue as with #71 .

**Comment by lukasewvd** [comment]
This should be fixed now, if not tell us and we will reopen the issue.
