### ISSUE TITLE
Some stages not showing previously created instances

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#74]
Most of our stages list all instances of that stage in sequence. See screenshot below. I just realized that 3 of our stages don't have that feature.
![image](https://user-images.githubusercontent.com/36447512/38890315-4d8ea116-4281-11e8-8858-5104ae20465a.png)

1) Lab results - Qffb7tI7jT7  OR BjNpOxjvEj5 The one in the MCH program: WSGAb5XwJ3Y
2) Newborn care 1 - FRSZV43y35y (Interestingly, when you add Newborn care subsequent (fSE8JyGdsV6), it shows the list of stages
3) Ultrasound results - I don't know the UID. Somehow this program stage is not listed in the program stages using api. And with 2.29, we no longer have 'Show details' on program stage for me to get the UID

This is how these 3 stages look
![image](https://user-images.githubusercontent.com/36447512/38890275-38e7b162-4281-11e8-972d-3d66f8e85904.png)

**Comment by Bekkalizer** [comment]
These stages is using the "compare form" mode as they always have? Did something change for you?

**Comment by AkubaD** [comment]
@Bekkalizer 
I created a new user and put in 4 LAB events in chronological order. The screen looks the same. Look like there is a bug

**Comment by lukasewvd** [comment]
This should be fixed now (after new deploy).
