### ISSUE TITLE
Full profile does not load when creating new TEI

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#76]
This used to be in #68 - the decoupling of program stages.
When you try to register a person, it sometimes does not give the full profile page and you have to restart the registration, and sometimes have to clear cache as well. It is easier to reproduce on the training instance: http://103.247.238.74:8081/dhistr/api/apps/E-Registry/index.html
Your logins on Dev should work here as well.

![image](https://user-images.githubusercontent.com/36447512/39118188-10e3a1be-46e9-11e8-8680-9119f8c03122.png)

**Comment by lukasewvd** [comment]
This commit should fix this issue: https://github.com/HRHR-project/e-registry-app/commit/8fc9a2ce8c0cc226087500ab477b0fa5f2321280. If not tell us and we will re-open the issue.
