### ISSUE TITLE
Cannot see  any events in MCH or create any events in any program

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#8]
I found a previously entered woman. When I opened her record in the MCH program, there were no events, or any way to create events. It just had 'Main menu' and nothing else. There are no buttons for creating a Referral, Creating a new event, etc.
This woman happened to be registered in 2 other programs- Client Register, and Old_Pregnancy Register. For both of those programs, you can see events that have been previously created (unlike for the MCH program). And the buttons for adding new events exist (unlike for the MCH program). BUT when you try to create an event, you get an error saying 'All expected events are already present. cannot create more events'. Even though this program has several other stages with no instances created yet.
Record is https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html#/dashboard?tei=u6tVjOAIipM&program=WSGAb5XwJ3Y

**Comment by AkubaD** [comment]
Also, I was looking at this record as a super user. So it should not be a permissions issue...

**Comment by zepto5** [comment]
MCH program, Main menu:
I just updated the e-registry-app. Main menu should now show program stages. 
It may be more to here. Please test and see if it works like expected.
