### ISSUE TITLE
Cannot select Union name in registration

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#80]
Union name drop down looks different in search, compared to registration and Profile edit

Here is how it looks in registration. When it looks like this, you cannot select anything. You click and nothing is selected. This is a list of all the org units in the system, which we don't want. We only want the Unions. See the second screenshot below
![image](https://user-images.githubusercontent.com/36447512/39427054-9a3c1a6a-4c82-11e8-9650-e28892657725.png)

This is how it looks in Search (and Profile edit) - only the unions show, and you can select a union. This is how we want it to look in Registration.
![image](https://user-images.githubusercontent.com/36447512/39427162-11ccec58-4c83-11e8-9706-65c6e57a656a.png)

**Comment by lukasewvd** [comment]
Should be fixed now (after deploy).
