### ISSUE TITLE
Attribute list doesn't load for registration

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#82]
I keep getting this screen after I click to register a new TEI. 
Clearing cache did not resolve it. I had to log out and log back in

![image](https://user-images.githubusercontent.com/36447512/39428209-e36f249e-4c86-11e8-846b-dc675970bcdc.png)

**Comment by lukasewvd** [comment]
@AkubaD Is this a one-time incident or does it happen again after you log out and then in again?

**Comment by AkubaD** [comment]
Hi @lukasewvd 
It seemed to be one time - it didn't happen again after I logged out and logged in again. But another colleague had the same experience earlier today: No attributes loading, and fixed after logging out and logging back in

**Comment by lukasewvd** [comment]
Could be related to the deploy. Sometimes you need to do a browser cache clean after a new deploy has been done. I will keep this issue up for a bit, but if it does not happen again I will close the issue.

**Comment by AkubaD** [comment]
@lukasewvd should you need to do a cache clean if you consistently use a new incognito window?

**Comment by lukasewvd** [comment]
No, in _theory_ not.

**Comment by AkubaD** [comment]
@lukasewvd 
It just happened again. I opened a new incognito window and tried to create a new TEI and got no attributes loading.
I logged out and logged in as another user and it was ok. Also logged out and logged back in as the original user and it was ok as well.

**Comment by lukasewvd** [comment]
Did you check the console for errors?

**Comment by AkubaD** [comment]
Oops, sorry I didn't, Will do if it happens again

**Comment by AkubaD** [comment]
@lukasewvd 
Here you go. I got it to happen again by opening a new incognito window and logging in as a different user
![image](https://user-images.githubusercontent.com/36447512/39512081-e524e3ae-4def-11e8-9584-1d3a573b4d4b.png)

This is what console looks like when I re-login and the issue does not appear. The error in the console is also gone
![image](https://user-images.githubusercontent.com/36447512/39512205-59174fcc-4df0-11e8-9402-10ac30811247.png)

**Comment by AkubaD** [comment]
I also get these errors when I try to clear cache

![image](https://user-images.githubusercontent.com/36447512/39512314-d050ff8e-4df0-11e8-8ee4-6c8a7f234f1a.png)

AND THEN, the original issue and error show up again after I clear cache. Note that the issue had gone after I re-logged in, and now it is back within the same login session, but only after I cleared cache. 
![image](https://user-images.githubusercontent.com/36447512/39512463-6224878c-4df1-11e8-81e2-7c26d9a5f61c.png)

**Comment by lukasewvd** [comment]
@AkubaD What user are you using?

**Comment by lukasewvd** [comment]
I was able to reproduce it now.

**Comment by AkubaD** [comment]
It doesn't seem to matter which user. I have used mCHCP_int1, mCHCP_cont, CHCP_int_trial1
All with password eReg!234
All gave the same pattern of behavior

**Comment by lukasewvd** [comment]
I have made a fix for this issue, has not been properly tested, but from what I am seeing it should work. Keeping the issue open till it has been tested.
