### ISSUE TITLE
Make newborn stages not 'Compare form'

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#84]
Hi @Bekkalizer @lukasewvd 
Referecing issue #74, Bangladesh would want the Newborn 1 stage FRSZV43y35y to NOT be in the current 'Compare form'.
We would want it to be like ANC1 and PNC1. The newborn subsequent visit (fSE8JyGdsV6) is already in the ANC/PNC form, so no need to touch that.
Thanks

**Comment by lukasewvd** [comment]
Should be fixed now (after new deploy).
