### ISSUE TITLE
Can Clear cache buttons be put at top of page?

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#86]
Since we use clear cache to solve quite a few issues, can we make the process more user friendly by having the Select all and Clear buttons at the top of the page instead of the bottom? No one (certainly not our users) looks at the list of things to clear. We always select all, so there's no need to scroll down to look through the list.

![image](https://user-images.githubusercontent.com/36447512/39512558-b102d142-4df1-11e8-86e1-31ad53efbf7b.png)

**Comment by lukasewvd** [comment]
@AkubaD We do not work on the cache cleaner app. If you want a change in the app you can request an improvement for the app on the DHIS2 JIRA: https://jira.dhis2.org.
