### ISSUE TITLE
New error on registration: check import summary

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#87]
This is a new error I have not seen before. It is happening consistently when I try to create a new TEI
The warnings in the console are related to a program rule that has not been edited/corrected for a while, so I doubt it that has anything to do with it
![image](https://user-images.githubusercontent.com/36447512/39513500-da727782-4df4-11e8-9356-227cd0d2f17d.png)
Trying a second time
![image](https://user-images.githubusercontent.com/36447512/39513512-e5955472-4df4-11e8-8b74-ce4130ba1cf1.png)

**Comment by lukasewvd** [comment]
@AkubaD If you see this issue again, could you double-click the link next to the red POST and take a screenshot?

**Comment by lukasewvd** [comment]
I this still happening?

**Comment by lukasewvd** [comment]
Not able to reproduce, tell me if it still is happening and I will open the issue again.
