### ISSUE TITLE
Program stages moved around, seemingly on their own...

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#88]
I had our program stages in a particular sequence so they would show up in a particular sequence in the menu for our users.
I just noticed today they have been moved completely out of sequence. No one seems to have done it manually, and it would have been a lot of work to do it manually.
Any clues how this could have happened? 

![image](https://user-images.githubusercontent.com/36447512/39514605-f07bd1f6-4df7-11e8-8193-c24159ecd5d3.png)

**Comment by lukasewvd** [comment]
We do not work on the Maintenance app, we only work on the eRegistry, tracker-capture and event-capture app. You can report the bug on the DHIS2 JIRA: https://jira.dhis2.org.
