### ISSUE TITLE
Persistent error on data entry

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#89]
This is new today. 
This pops up with every data entry that is supposed to run a rule, ANY rule.  The data element referenced does not get hidden, even though the pop-up says it is. And that Hide data element action is in only 1 rule. After that rule first got triggered, now it is triggered with ANY data entry in the page
![image](https://user-images.githubusercontent.com/36447512/39518965-2ecb42d6-4e05-11e8-8776-64b6a5544549.png)

Here is how the whole page looks like with a repeated error in the console
![image](https://user-images.githubusercontent.com/36447512/39519025-6c0a7108-4e05-11e8-99e9-e9826f4f7a12.png)

Here is the detail of the error 
angular.js:9866 POST https://bd-eregistry.dhis2.org/dhis/api/29/events.json 409 (Conflict)
(anonymous function) @ angular.js:9866
n @ angular.js:9667f @ angular.js:9383
(anonymous function) @ angular.js:13248
$eval @ angular.js:14466
$digest @ angular.js:14282
$apply @ angular.js:14571
l @ angular.js:9698
M @ angular.js:9888
F.onload @ angular.js:9829

**Comment by AkubaD** [comment]
Actually, the rule that hides the BMI data element and triggers the pop-up uses the new hasUserRole function. ID bmbzlnEnfHS
Maybe that is related...

**Comment by RahmanMonjur** [comment]
stop generating BMI by adding the below line in condition of rule rulePEx1015 

&& !(d2:hasUserRole('moQCqVTW1Kz') || d2:hasUserRole('c9QQ5Jr4Fmy'))

**Comment by lukasewvd** [comment]
@AkubaD have you tried @RahmanMonjur's solution?
