### ISSUE TITLE
System now requiring entry of enrollment date for MCH program only

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#91]
It used to be when you created a tracked entity in our Client register program, and then enrolled in the MCH program, you did not need to enter anything else (because they have the same attributes). Clicking Enroll completed the enrollment immediately.
Since the latest deploy, we now have the system requiring that the user enter the enrollment date.
How do you make the date of enrollment prefilled (and editable) for the MCH program?
Here are the enrollment settings for the program.
![image](https://user-images.githubusercontent.com/36447512/39705251-20f21222-520e-11e8-95c5-bf985fea2544.png)

Here is the blank enrollment field - date of pregnancy enrollment
![image](https://user-images.githubusercontent.com/36447512/39707192-f47253a0-5213-11e8-9e32-931256b43578.png)

**Comment by RahmanMonjur** [comment]
@lukasewvd : I did a trick in enrolment-dates-form.html file. After line 28, I've put 
ng-init="selectedEnrollment.enrollmentDate = selectedEnrollment.enrollmentDate || today"
and got the today's date if the controller couldn't fetch enrolmentDate.

**Comment by AkubaD** [comment]
@Bekkalizer Could you have someone take a look at this? It is an additional, unnecessary step in our workflow that we did not have previously and would like it to be as it was. Monjur had a possible solution in the previous comment

**Comment by Bekkalizer** [comment]
Hey, if Monjour tests his code and sends a git pull request, we can do a review and merge it into the app!

**Comment by AkubaD** [comment]
Hi MonjurPlease see Markus' suggestion below to test your solution to this and send a git pull request. Akuba

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 5, 2018 at 12:48 PM, Markus Bekken<notifications@github.com> wrote:   Hey, if Monjour tests his code and sends a git pull request, we can do a review and merge it into the app!

**Comment by AkubaD** [comment]
@rah

**Comment by RahmanMonjur** [comment]
Its working, this issue can be closed.

**Comment by AkubaD** [comment]
@RahmanMonjur I have not seen the enrolmentDate bug you mentioned so I am closing this issue. thanks for your assistance with it.
