### ISSUE TITLE
TEI created in program says it is not enrolled in that program

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#93]
When you create a TEI in the client register program (that is our workflow), it says there is no active enrollment and asks that you enroll.
I'm not sure how this is possible since the TEI has created with the client register program selected for enrollment.
When you click to enroll, it enrolls okay

![image](https://user-images.githubusercontent.com/36447512/40010194-58d9e336-57a4-11e8-8333-04a896b98fad.png)

**Comment by lukasewvd** [comment]
Seems like this has been fixed. If not, tell me and I will reopen the issue.
