### ISSUE TITLE
"enrolling clinic" changes to OU of user viewing enrollment

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#95]
Search for user shows a different registering org unit
![image](https://user-images.githubusercontent.com/36451485/40666829-f2102444-6360-11e8-9b05-a6ae40797bb4.png)

It has switched to the OU that searched for the enrollment
![image](https://user-images.githubusercontent.com/36451485/40666896-1a73cb84-6361-11e8-8fd7-6c8d5f546395.png)

Then you switch to a new OU for search
![image](https://user-images.githubusercontent.com/36451485/40667075-8f2a914c-6361-11e8-8913-0e6e0cc1fbb9.png)

And the enrolling OU changes again.
![image](https://user-images.githubusercontent.com/36451485/40667136-ae35a112-6361-11e8-94c9-5c3904a3755c.png)

Please keep the registering unit fixed on the stage menu page.

**Comment by lukasewvd** [comment]
This should now be fixed.
