### ISSUE TITLE
cannot view previous events entered elsewhere

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#96]
Thought this was a flaw in the Android app, but it appears to be an issue with latest eReg app code.

I can see previous events for a TEI enrollment, Joly, when I am logged in as a superuser. I can see all events entered previously.
![image](https://user-images.githubusercontent.com/36451485/40671135-5005e46c-636b-11e8-87b4-d6bfee9c56e9.png)

But then I access a TEI enrollment as a model Android user (fwa7) or eRegistry app user (chcp_int1) And I cannot see any events. I still have access to add new stages.
![image](https://user-images.githubusercontent.com/36451485/40671158-688e55aa-636b-11e8-9e11-b7aef21f29cd.png)

I dont think this is not a user permissions issue. When I perform same process on the training instance as the same CHCP user, I can see the events just fine.
![image](https://user-images.githubusercontent.com/36451485/40671247-a521716e-636b-11e8-947d-37f58c874a2d.png)

@Wonfrost  @Bekkalizer this seems to be a major bug.

**Comment by zepto5** [comment]
This looks like the bug we fixed at friday. Can this be closed?

**Comment by lukasewvd** [comment]
Closing this issue, if bug still exists, tell me and i will reopen the issue.
