### ISSUE TITLE
Errors on cache clearing

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#97]
GET https://bd-eregistry.dhis2.org/dhis/dhis-web-core-resource/dhis/dhis2-util-1554e6a5ab.js 404 (Not Found)
GET https://bd-eregistry.dhis2.org/dhis/dhis-web-core-resource//fonts/roboto.css 500 (Internal Server Error)

![image](https://user-images.githubusercontent.com/36447512/40831541-966b929c-6589-11e8-8ba2-d425c2a11c69.png)

**Comment by lukasewvd** [comment]
The Cache cleaner app is a separate app and I therefore suggest creating a JIRA issue here: https://jira.dhis2.org/secure/Dashboard.jspa.
