### ISSUE TITLE
Error on enrollment in creation of TEI - enrollment in Client register program

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#98]
angular.js:9866 
GET https://bd-eregistry.dhis2.org/dhis/api/29/userSettings/keyTrackerDashboardLayout 404 (Not Found)

![image](https://user-images.githubusercontent.com/36447512/40831872-6f9d0db6-658a-11e8-8a01-4c205967a01e.png)

**Comment by zepto5** [comment]
Not actually an error. Client checks for something in the userSettings. If its not found, the browser throws an 404 not found message. This can be ignored.
