### ISSUE TITLE
Error related to _getHighRIskPregnancy

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#99]
I got this error when creating a new stage (not in the MCH program)
And the rules in that stage don't seem to be running. All but the first data element are supposed to be hidden
angular.js:11655 TypeError: Cannot read property 'concat' of undefined
    at _getHighRiskPregnancy 
![image](https://user-images.githubusercontent.com/36447512/40832361-6ca3cba8-658b-11e8-9d86-9b655ccedd26.png)

**Comment by AkubaD** [comment]
@zepto5
@Bekkalizer asked for you to look at this

**Comment by zepto5** [comment]
The rules should now be running
